# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  name: SmugglerCode_SelfHosted

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  packageOutput: '$(Build.ArtifactStagingDirectory)/nuget'

steps:

- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '9.0.x'

- script: dotnet --info
  displayName: 'Show dotnet info'
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: DotNetCoreCLI@2
  displayName: 'Build solution'
  inputs:
    command: 'build'
    projects: '$(solution)'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'Run tests'
  inputs:
    command: 'test'
    projects: '**/*Tests.csproj'
    arguments: '--configuration $(buildConfiguration)'

# Create nuget package of the Blazor UI project 
- task: DotNetCoreCLI@2
  displayName: 'dotnet pack'
  inputs:
    command: pack
    packagesToPack: SmugglerCode.Blazor.UI\SmugglerCode.Blazor.UI.csproj
    packDirectory: '$(Build.ArtifactStagingDirectory)\SmugglerCode.Blazor.UI'

- task: DotNetCoreCLI@2
  displayName: 'Push to NuGet.org'
  inputs:
    command: custom
    custom: nuget
    arguments: >
      push $(Build.ArtifactStagingDirectory)\SmugglerCode.Blazor.UI\*.nupkg
      --api-key $(nuget_api_key)
      --source https://api.nuget.org/v3/index.json
      --skip-duplicate
